#!/bin/bash
#
# Portions of Models-3/CMAQ software were developed or based on information
# from various groups: Federal Government employees, contractors working on a
# United States Government contract, and non-Federal sources (including
# research institutions).  These research institutions have given the
# Government permission to use, prepare derivative works, and distribute copies
# of their work in Models-3/CMAQ to the public and to permit others to do so.
# EPA therefore grants similar permissions for use of the Models-3/CMAQ
# software, but users are requested to provide copies of derivative works to
# the Government without restrictions as to use by others.  Users are
# responsible for acquiring their own copies of commercial software associated
# with Models-3/CMAQ and for complying with vendor requirements.  Software
# copyrights by the MCNC Environmental Modeling Center are used with their
# permissions subject to the above restrictions.
#
# Author: Lucas A. J. Bastien

export FC=gfortran
export FC_FLAG_MOD="-J"
export F77_FLAGS="-ffixed-line-length-none -fmax-errors=1 -cpp"
export F90_FLAGS="-fmax-errors=1 -cpp"
export FOPT_FLAGS="-O2"

export CC=gcc
export C_FLAGS=""

export LINK_FLAGS=""

echo "In environment-user setup, HOME is set to $HOME"  # actually, still as /root, not sure where it was  / in some? container build env
SRC_BASE=/
echo "In environment-user setup, SRC_BASE is set to $SRC_BASE"  


##export DIR_REPO=/gpanda/ljin/Shared/CMAQ-4.5-ADJ-LAJB_tutorial/code/CMAQ-4.5-ADJ-LAJB
export DIR_REPO=$SRC_BASE/Downloads/CMAQ/CMAQ-4.5-ADJ-LAJB_tutorial/code/CMAQ-4.5-ADJ-LAJB     # expect /Downloads/CMAQ/CMAQ-4.5-ADJ-LAJB_tutorial/code/CMAQ-4.5-ADJ-LAJB
export DIR_INSTL=$DIR_REPO/built_gcc_gfortran_serial_BENZ
##export DIR_IOAPI=/gpanda/ljin/Shared/CMAQ-4.5-ADJ-LAJB_tutorial/code/IOAPI-3.0/built_nocpl_gcc_gfortran_s
export DIR_IOAPI=$SRC_BASE/Downloads/CMAQ/Api/ioapi/
##export DIR_NETCDF=/gpanda/software/sl-6.x86_64/modules/netcdf/4.2.1.1
export DIR_NETCDF=/usr/local/lib
##export DIR_MPI=/gpanda/software/sl-6.x86_64/modules/openmpi/1.6.5
export DIR_MPI=/usr/lib64/openmpi/bin

# Name of the FORTRAN netcdf library (in some installation, the C and FORTRAN
# netcdf libraries are put together in libnetcdf while in some other
# installation, the FORTRAN library is in a separate file called netcdff)
export LIB_NETCDF=-lnetcdff

# If the variable ParOpt is defined (not matter what its value is, even empty),
# then CCTM is compiled with parallel support.
#export ParOpt=""
export ModInpt=profile
export ModMech=mc_noop
export Mechanism=BENZ
export ModDriver=ctm
export ModInit=init
export ModAdjc=denrate
export ModCpl=gencoor
export ModHadv=hppm
export ModVadv=vppm
export ModHdiff=multiscale
export ModVdiff=eddy
export ModPhot=phot
export ModPing=ping_noop
export ModChem=chem_noop
export ModAero=aero_noop
export ModAdepv=aero_depv_noop
export ModCloud=cloud_noop
export ModPa=pa
export ModUtil=util
export PAOpt=pa_noop
export ModAdjChem=noop
# Emissions will be processed in chem if Cemis is defined and in vdiff
# otherwise.
## export Cemis ""

# Define the variable DIR_INC_TRAC to use a folder other than the default
#export DIR_INC_TRAC=$DIR_INSTL/tracer0

# Source the common resources
source $DIR_REPO/environment
